[project]
name = "bathymesh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "geopandas>=1.1.1",
    "gmsh>=4.14.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "mapbox-earcut>=1.0.3",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "open3d>=0.19.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "pygmsh>=7.1.17",
    "pymeshlab>=2025.7",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "scikit-image>=0.25.2",
    "shapely>=2.1.2",
    "svgwrite>=1.4.3",
    "tqdm>=4.66.0",
    "triangle>=20250106",
    "xarray>=2025.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["python/bathymesh"]
