// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DefaultsApiConfigDefaultsGetData, DefaultsApiConfigDefaultsGetResponses, GetProjectConfigApiConfigProjectIdGetData, GetProjectConfigApiConfigProjectIdGetErrors, GetProjectConfigApiConfigProjectIdGetResponses, HealthCheckApiHealthGetData, HealthCheckApiHealthGetResponses, RootGetData, RootGetResponses, SetProjectConfigApiConfigProjectIdPutData, SetProjectConfigApiConfigProjectIdPutErrors, SetProjectConfigApiConfigProjectIdPutResponses, ValidateProjectConfigApiConfigValidatePostData, ValidateProjectConfigApiConfigValidatePostErrors, ValidateProjectConfigApiConfigValidatePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health Check
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Defaults
 */
export const defaultsApiConfigDefaultsGet = <ThrowOnError extends boolean = false>(options?: Options<DefaultsApiConfigDefaultsGetData, ThrowOnError>) => (options?.client ?? client).get<DefaultsApiConfigDefaultsGetResponses, unknown, ThrowOnError>({ url: '/api/config/defaults', ...options });

/**
 * Get Project Config
 */
export const getProjectConfigApiConfigProjectIdGet = <ThrowOnError extends boolean = false>(options: Options<GetProjectConfigApiConfigProjectIdGetData, ThrowOnError>) => (options.client ?? client).get<GetProjectConfigApiConfigProjectIdGetResponses, GetProjectConfigApiConfigProjectIdGetErrors, ThrowOnError>({ url: '/api/config/{project_id}', ...options });

/**
 * Set Project Config
 */
export const setProjectConfigApiConfigProjectIdPut = <ThrowOnError extends boolean = false>(options: Options<SetProjectConfigApiConfigProjectIdPutData, ThrowOnError>) => (options.client ?? client).put<SetProjectConfigApiConfigProjectIdPutResponses, SetProjectConfigApiConfigProjectIdPutErrors, ThrowOnError>({
    url: '/api/config/{project_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validate Project Config
 */
export const validateProjectConfigApiConfigValidatePost = <ThrowOnError extends boolean = false>(options: Options<ValidateProjectConfigApiConfigValidatePostData, ThrowOnError>) => (options.client ?? client).post<ValidateProjectConfigApiConfigValidatePostResponses, ValidateProjectConfigApiConfigValidatePostErrors, ThrowOnError>({
    url: '/api/config/validate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
