// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_set_project_image_api_image__project_id__put
 */
export type BodySetProjectImageApiImageProjectIdPut = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ContourExtractionConfig
 */
export type ContourExtractionConfig = {
    /**
     * Min Polygon Area
     *
     * Minimum polygon area for contour extraction
     */
    min_polygon_area: number;
    /**
     * Simplify Tolerance
     *
     * Tolerance for simplifying extracted contours
     */
    simplify_tolerance: number;
    /**
     * Max Segments
     *
     * Maximum number of segments for contour extraction
     */
    max_segments: number;
    /**
     * Min Area Fraction
     *
     * Minimum area fraction for contour extraction
     */
    min_area_fraction: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeighmapProcessingConfig
 */
export type HeighmapProcessingConfig = {
    /**
     * Exterior Buffer Width
     */
    exterior_buffer_width: number;
    /**
     * Exterior Buffer Value
     */
    exterior_buffer_value: number;
    /**
     * Data Offset
     */
    data_offset: number;
    mesh_units: MeshUnits;
    /**
     * Thresholds
     *
     * List of height thresholds for each level
     */
    thresholds: Array<number>;
    /**
     * Base Height
     *
     * Z-coordinate of the base level
     */
    base_height: number;
    /**
     * Layer Thickness
     *
     * Thickness of each extruded layer
     */
    layer_thickness: number;
};

/**
 * HeightmapDataJson
 */
export type HeightmapDataJson = {
    /**
     * Data
     */
    data: Array<Array<number>>;
};

/**
 * HeightmapParams
 */
export type HeightmapParams = {
    /**
     * Is Preview
     */
    is_preview: boolean;
    /**
     * Max Dimension Override
     */
    max_dimension_override?: number | null;
};

/**
 * ImageProcessingConfig
 */
export type ImageProcessingConfig = {
    /**
     * Preserve Full Resolution
     *
     * Whether to preserve full image resolution
     */
    preserve_full_resolution: boolean;
    /**
     * Max Dimension
     *
     * Maximum dimension (width/height) for resizing images
     */
    max_dimension: number | null;
    /**
     * Region
     *
     * Region of interest in the format (left, upper, right, lower)
     */
    region: [
        number,
        number,
        number,
        number
    ] | null;
    /**
     * Fill Nan Values
     *
     * Whether to fill NaN values in images
     */
    fill_nan_values: boolean;
    /**
     * Fill Max Iterations
     *
     * Maximum iterations for filling NaN values
     */
    fill_max_iterations: number;
    /**
     * Fill Neighborhood
     *
     * Neighborhood size for filling NaN values
     */
    fill_neighborhood: number;
    /**
     * Color Map
     *
     * Color to value mapping with fuzziness
     */
    color_map: {
        [key: string]: unknown;
    };
    /**
     * Default Fuzziness
     *
     * Default fuzziness value (Delta E) when not specified
     */
    default_fuzziness: number;
};

/**
 * JobStatus
 */
export type JobStatus = {
    /**
     * Jobid
     */
    jobId: string;
    /**
     * Status
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
    /**
     * Jobtype
     */
    jobType: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Startedat
     */
    startedAt?: string | null;
    /**
     * Completedat
     */
    completedAt?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MeshCombinationConfig
 */
export type MeshCombinationConfig = {
    /**
     * Merge Threshold
     *
     * Threshold for merging close vertices when combining meshes
     */
    merge_threshold: number;
};

/**
 * MeshGenerationConfig
 */
export type MeshGenerationConfigInput = {
    /**
     * Stateless
     *
     * Whether to run in stateless mode (no visualizations)
     */
    stateless: boolean;
    heightmap_processing: HeighmapProcessingConfig;
    mesh_combination: MeshCombinationConfig;
    contour_extraction: ContourExtractionConfig;
    triangulation: TriangulationConfig;
    post_processing: PostProcessingConfig;
};

/**
 * MeshGenerationConfig
 */
export type MeshGenerationConfigOutput = {
    /**
     * Stateless
     *
     * Whether to run in stateless mode (no visualizations)
     */
    stateless: boolean;
    heightmap_processing: HeighmapProcessingConfig;
    mesh_combination: MeshCombinationConfig;
    contour_extraction: ContourExtractionConfig;
    triangulation: TriangulationConfig;
    post_processing: PostProcessingConfig;
};

/**
 * MeshUnits
 *
 * Scaling parameters for mesh generation.
 */
export type MeshUnits = {
    /**
     * Units X
     */
    units_x: number;
    /**
     * Units Y
     */
    units_y: number;
    /**
     * Units Z
     */
    units_z: number;
};

/**
 * PostProcessingConfig
 */
export type PostProcessingConfig = {
    /**
     * Apply Post Processing
     *
     * Whether to apply post-processing to meshes
     */
    apply_post_processing: boolean;
    /**
     * Remove Degenerate Triangles
     *
     * Remove degenerate triangles
     */
    remove_degenerate_triangles: boolean;
    /**
     * Remove Duplicated Vertices
     *
     * Remove duplicated vertices
     */
    remove_duplicated_vertices: boolean;
    /**
     * Remove Duplicated Triangles
     *
     * Remove duplicated triangles
     */
    remove_duplicated_triangles: boolean;
    /**
     * Remove Unreferenced Vertices
     *
     * Remove unreferenced vertices
     */
    remove_unreferenced_vertices: boolean;
    /**
     * Merge Close Vertices
     *
     * Merge vertices that are very close
     */
    merge_close_vertices: boolean;
    /**
     * Merge Vertices Threshold
     *
     * Distance threshold for merging vertices
     */
    merge_vertices_threshold: number;
    /**
     * Simplification Method
     *
     * Method for mesh simplification
     */
    simplification_method: string;
    /**
     * Target Triangle Count
     *
     * Target triangle count for mesh simplification
     */
    target_triangle_count: number;
    /**
     * Voxel Size
     *
     * Voxel size for vertex clustering simplification
     */
    voxel_size: number;
};

/**
 * ProjectConfig
 */
export type ProjectConfigInput = {
    /**
     * Project Id
     *
     * Unique identifier for the project
     */
    project_id: string;
    mesh_generation: MeshGenerationConfigInput;
    image_processing: ImageProcessingConfig;
};

/**
 * ProjectConfig
 */
export type ProjectConfigOutput = {
    /**
     * Project Id
     *
     * Unique identifier for the project
     */
    project_id: string;
    mesh_generation: MeshGenerationConfigOutput;
    image_processing: ImageProcessingConfig;
};

/**
 * TriangulationConfig
 */
export type TriangulationConfig = {
    /**
     * Triangulator Add Interior Points
     *
     * Whether to add interior points during triangulation
     */
    triangulator_add_interior_points: boolean;
    /**
     * Triangulator Interior Point Density
     *
     * Density of interior points (points per unit area)
     */
    triangulator_interior_point_density: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DefaultsApiConfigDefaultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/defaults';
};

export type DefaultsApiConfigDefaultsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectConfigOutput;
};

export type DefaultsApiConfigDefaultsGetResponse = DefaultsApiConfigDefaultsGetResponses[keyof DefaultsApiConfigDefaultsGetResponses];

export type ListProjectsApiProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListProjectsApiProjectsGetResponse = ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type GetProjectConfigApiConfigProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/config/{project_id}';
};

export type GetProjectConfigApiConfigProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectConfigApiConfigProjectIdGetError = GetProjectConfigApiConfigProjectIdGetErrors[keyof GetProjectConfigApiConfigProjectIdGetErrors];

export type GetProjectConfigApiConfigProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectConfigOutput;
};

export type GetProjectConfigApiConfigProjectIdGetResponse = GetProjectConfigApiConfigProjectIdGetResponses[keyof GetProjectConfigApiConfigProjectIdGetResponses];

export type SetProjectConfigApiConfigProjectIdPutData = {
    body: ProjectConfigInput;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/config/{project_id}';
};

export type SetProjectConfigApiConfigProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetProjectConfigApiConfigProjectIdPutError = SetProjectConfigApiConfigProjectIdPutErrors[keyof SetProjectConfigApiConfigProjectIdPutErrors];

export type SetProjectConfigApiConfigProjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ValidateProjectConfigApiConfigValidatePostData = {
    body: ProjectConfigInput;
    path?: never;
    query?: never;
    url: '/api/config/validate';
};

export type ValidateProjectConfigApiConfigValidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateProjectConfigApiConfigValidatePostError = ValidateProjectConfigApiConfigValidatePostErrors[keyof ValidateProjectConfigApiConfigValidatePostErrors];

export type ValidateProjectConfigApiConfigValidatePostResponses = {
    /**
     * Response Validate Project Config Api Config Validate Post
     *
     * Successful Response
     */
    200: boolean;
};

export type ValidateProjectConfigApiConfigValidatePostResponse = ValidateProjectConfigApiConfigValidatePostResponses[keyof ValidateProjectConfigApiConfigValidatePostResponses];

export type GetProjectImageApiImageProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Max Dimension
         */
        max_dimension?: number | null;
    };
    url: '/api/image/{project_id}';
};

export type GetProjectImageApiImageProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectImageApiImageProjectIdGetError = GetProjectImageApiImageProjectIdGetErrors[keyof GetProjectImageApiImageProjectIdGetErrors];

export type GetProjectImageApiImageProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SetProjectImageApiImageProjectIdPutData = {
    body: BodySetProjectImageApiImageProjectIdPut;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Update Config Colormap
         */
        update_config_colormap?: boolean;
    };
    url: '/api/image/{project_id}';
};

export type SetProjectImageApiImageProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetProjectImageApiImageProjectIdPutError = SetProjectImageApiImageProjectIdPutErrors[keyof SetProjectImageApiImageProjectIdPutErrors];

export type SetProjectImageApiImageProjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectHeightmapApiHeightmapProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query: {
        /**
         * Is Preview
         */
        is_preview: boolean;
    };
    url: '/api/heightmap/{project_id}';
};

export type GetProjectHeightmapApiHeightmapProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectHeightmapApiHeightmapProjectIdGetError = GetProjectHeightmapApiHeightmapProjectIdGetErrors[keyof GetProjectHeightmapApiHeightmapProjectIdGetErrors];

export type GetProjectHeightmapApiHeightmapProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: HeightmapDataJson;
};

export type GetProjectHeightmapApiHeightmapProjectIdGetResponse = GetProjectHeightmapApiHeightmapProjectIdGetResponses[keyof GetProjectHeightmapApiHeightmapProjectIdGetResponses];

export type CalculateProjectHeightmapApiHeightmapProjectIdPostData = {
    /**
     * Params
     */
    body: HeightmapParams | null;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/heightmap/{project_id}';
};

export type CalculateProjectHeightmapApiHeightmapProjectIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CalculateProjectHeightmapApiHeightmapProjectIdPostError = CalculateProjectHeightmapApiHeightmapProjectIdPostErrors[keyof CalculateProjectHeightmapApiHeightmapProjectIdPostErrors];

export type CalculateProjectHeightmapApiHeightmapProjectIdPostResponses = {
    /**
     * Successful Response
     */
    200: JobStatus;
};

export type CalculateProjectHeightmapApiHeightmapProjectIdPostResponse = CalculateProjectHeightmapApiHeightmapProjectIdPostResponses[keyof CalculateProjectHeightmapApiHeightmapProjectIdPostResponses];

export type GetJobStatusApiJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobStatusApiJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobStatusApiJobsJobIdGetError = GetJobStatusApiJobsJobIdGetErrors[keyof GetJobStatusApiJobsJobIdGetErrors];

export type GetJobStatusApiJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobStatus;
};

export type GetJobStatusApiJobsJobIdGetResponse = GetJobStatusApiJobsJobIdGetResponses[keyof GetJobStatusApiJobsJobIdGetResponses];
